palavra = input("Digite algo: ")    
print("O tipo do valor é:  ", type(palavra))
print("Só tem espaços: ", palavra.isspace())
print("É um numero: ", palavra.isnumeric())
print("É alfabético: ", palavra.isalpha())
print("É alfanumerico: ", palavra.isalnum())
print("É maiúscula: ", palavra.isupper())
print("É minúscula: ", palavra.islower())
print("Ela tem maiúscula e minúscula: ", palavra.istitle())