n = int(input("Digite um número para verificar sua taboada: "))
print("===============")
print("{:^3} x  1 = {:^3}".format(n, n*1))
print("{:^3} x  2 = {:^3}".format(n, n*2))
print("{:^3} x  3 = {:^3}".format(n, n*3))
print("{:^3} x  4 = {:^3}".format(n, n*4))
print("{:^3} x  5 = {:^3}".format(n, n*5))
print("{:^3} x  6 = {:^3}".format(n, n*6))
print("{:^3} x  7 = {:^3}".format(n, n*7))
print("{:^3} x  8 = {:^3}".format(n, n*8))
print("{:^3} x  9 = {:^3}".format(n, n*9))
print("{:^3} x 10 = {:^3}".format(n, n*10))
print("===============")